import React ,{useState}from 'react';
import Head from 'next/head'

const landpage_5 = () => {


    

    return (
        <>
         <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        </Head>  
     
        <div className="land5-background d-flex justify-content-center">
 
      <section className="land5-container">
    <div className="land5-section">
        <div className="land5-main  ">

  <div className="featured-heading-parent"><h2 className="featured-heading">Featured in:</h2></div>
  
  <div className="featured-parent">
    <ul className="featured-ul d-flex">
      <li className="featured-li">
        <img src="https://www.broadbandgenie.co.uk/img/kazaam/logos/the-telegraph.png" alt="" className="featured-img" /></li>
      <li className="featured-li">
        <img src="https://www.broadbandgenie.co.uk/img/kazaam/logos/bbc.png" alt="" className="featured-img" /></li>
      <li className="featured-li">
        <img src="https://www.broadbandgenie.co.uk/img/kazaam/logos/independent.png" alt="" className="featured-img" /></li>
      <li className="featured-li">
        <img src="https://www.broadbandgenie.co.uk/img/kazaam/logos/theguardian.png" alt="" className="featured-img" /></li>
      <li className="featured-li">
        <img src="https://www.broadbandgenie.co.uk/img/kazaam/logos/mirror.png" alt="" className="featured-img" /></li>
    </ul>
  </div>


    </div>
       </div>   
       </section>

</div>

    
        </>
    )
}

export default landpage_5
